/* Generated by :claw at 2020-10-21T21:39:12.205379Z */

#include "tmx.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API tmx_col_floats* __claw_tmx_col_to_floats(tmx_col_floats* arg0, uint32_t arg1) {
  tmx_col_floats result = tmx_col_to_floats(arg1);
 (*arg0) = result;
  return arg0;
}

__CLAW_API tmx_col_bytes* __claw_tmx_col_to_bytes(tmx_col_bytes* arg0, uint32_t arg1) {
  tmx_col_bytes result = tmx_col_to_bytes(arg1);
 (*arg0) = result;
  return arg0;
}

#if defined(__cplusplus)
}
#endif
